---
version: '3.5'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    container_name: keycloak-dev
    restart: unless-stopped
    depends_on:
      - keycloak-db
    command: >
      start-dev
      --spi-theme-static-max-age=-1
      --spi-theme-cache-themes=false
      --spi-theme-cache-templates=false
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      # - KC_HOSTNAME=localhost
      - KC_HOSTNAME_PORT=8080
      - KC_DB_URL=jdbc:postgresql://keycloak-db/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=dah2at2yeithuuNgoo7lie9Afee8bo6r
      - KC_DB=postgres
    volumes:
      - ./theme/keywind:/opt/keycloak/themes/keywind-dev:ro
    networks:
      - default
      - keycloak
    ports:
      - 8080:8080

  keycloak-db:
    image: postgres:10-alpine
    container_name: keycloak-dev-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=dah2at2yeithuuNgoo7lie9Afee8bo6r
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - keycloak

volumes:
  keycloak-db-data:

networks:
  keycloak:
    internal: true
